# Alembic configuration
#
# Pour initialiser :
#   cd nbalance
#   alembic init alembic
#
# Puis remplacer alembic/env.py avec le contenu adapté.
#
# Pour créer une migration :
#   alembic revision --autogenerate -m "description"
#
# Pour appliquer :
#   alembic upgrade head

[alembic]
script_location = alembic
#sqlalchemy.url = postgresql://kuser:change_asap@amance.cirad.fr:5432/nbalance
sqlalchemy.url = postgresql://nbalance:nbalance_dev@coulmes.cirad.fr:5432/nbalance

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
